include:
- template: Auto-DevOps.gitlab-ci.yml

image: adoptopenjdk/openjdk11:ubi

stages:
  - build
  - package
  - test
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - performance
  - cleanup

build:
  image: adoptopenjdk/openjdk11:ubi
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 7 days

build_image:
  image: docker:latest
  stage: package
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE
    DOCKER_HOST: tcp://localhost:2375

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg JAR_FILE=build/libs/dylen-ego-network-service-0.1.0.jar .
    - docker push
