image: adoptopenjdk/openjdk11:ubi

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 30 days

test:
  stage: test
  script:
    - ./gradlew check

build_image:
  image: docker:latest
  script:
    - docker build --build-arg JAR_FILE=build/libs/dylen-ego-network-service-0.1.0.jar -t registry.gitlab.com/acdh-oeaw/dylen/dylen-ego-network-service .
