startupProbe:
  path: "/actuator/health/liveness"
  port: 5000
  initialDelaySeconds: 300
  timeoutSeconds: 30
  scheme: "HTTP"
  probeType: "httpGet"
  failureThreshold: 100
  periodSeconds: 15
livenessProbe:
  path: "/actuator/health/liveness"
  port: 5000
  initialDelaySeconds: 300
  timeoutSeconds: 20
  failureThreshold: 100
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/actuator/health/readiness"
  port: 5000
  initialDelaySeconds: 300
  timeoutSeconds: 20
  failureThreshold: 100
  scheme: "HTTP"
  probeType: "httpGet"
tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 6000
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 6000
resources:
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  requests:
#    cpu: 100m
    memory: 2000Mi
