startupProbe:
  path: "/actuator/health/liveness"
  port: 5000
  initialDelaySeconds: 15
  timeoutSeconds: 30
  scheme: "HTTP"
  probeType: "httpGet"
  failureThreshold: 50
  periodSeconds: 15
livenessProbe:
  path: "/actuator/health/liveness"
  port: 5000
  initialDelaySeconds: 180
  timeoutSeconds: 20
  failureThreshold: 20
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/actuator/health/readiness"
  port: 5000
  initialDelaySeconds: 60
  timeoutSeconds: 20
  failureThreshold: 20
  scheme: "HTTP"
  probeType: "httpGet"