replicaCount: 1
image:
  repository: $repository
  tag: "$tag"
  pullPolicy: Always
extraLabels:
  "ID": "$service_id"
gitlab:
  app: "$app_name"
  envURL: "$repo_url"
service:
  enabled: true
  name: "$app_name"
  url: "$public_url"
  additionalHosts:
    - ${app_name_in_url}-${ref_name}.${kube_ingress_base_domain}
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
ingress:
  enabled: true
  path: "/"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/proxy-read-timeout: "3600"
startupProbe:
  path: "/actuator/health/liveness"
  port: 5000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  scheme: "HTTP"
  probeType: "httpGet"
  failureThreshold: 100
  periodSeconds: 60
livenessProbe:
  path: "/actuator/health/liveness"
  port: 5000
  initialDelaySeconds: 120
  timeoutSeconds: 15
  failureThreshold: 100
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/actuator/health/readiness"
  port: 5000
  initialDelaySeconds: 120
  timeoutSeconds: 15
  failureThreshold: 100
  scheme: "HTTP"
  probeType: "httpGet"
tolerations:
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 6000
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 6000